import NavBar from "@/components/NavBar";
import "./globals.css";
import { Poppins } from 'next/font/google'
import Footer from "@/components/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "News App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${poppins.className} antialiased`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>

    </html>
  );
}
